server:
  port: ${SERVER_PORT:8088}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grocery_store
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: classpath:logback.xml

# application used properties
application:
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    session:
      expiration-in-hours: 24
    while-list-urls: /api/v1/auth/**;/api/v1/hello;/api/v1/users/**;



